site_name: TRAIL Ground Point Filtering
repo_url: https://github.com/3dgeo-heidelberg/trail-groundfiltering
docs_dir: ../docs
site_dir: ../site

theme:
  # logo: img/3DGeo_globe_white.svg     # light mode logo
  favicon: img/3dgeo.ico
  name: material
  custom_dir: overrides
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        # logo: img/3DGeo_globe_white.svg     # light mode logo
        primary: custom
        accent: custom
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        # logo: img/3DGeo_globe_red.png     # dark mode logo
        primary: custom
        accent: custom  # same as above
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  features:
    - search.highlight
    - content.code.copy
    - navigation.top
    - navigation.footer
use_directory_urls: false
extra_css:
  - customs.css
  - style.css
plugins:
  - mkdocs-jupyter:
      include_source: True
      include_requirejs: True
      ignore_h1_titles: True
  - search
  - mkdocs-pdf
markdown_extensions:
  - attr_list
  - abbr
  - md_in_html
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Installation: installation.md
  - AFwizard tutorials:
    - Study site 1: workflow_PK.ipynb
    - Study site 2: workflow_StA.ipynb
  - HELIOS++ tutorials:
    - Intro slides: helios.md
    - ALS simulation: helios_als.ipynb
    - ULS simulation: helios_uls.ipynb
    - Assessing AFwizard pipelines with LiDAR simulation: helios_for_afwizard.ipynb